# Generated by Django 4.2.20 on 2025-04-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
