version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: iceberen/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/var/www/foodgram/media/
    depends_on:
      - db
  frontend:
    image: iceberen/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/var/html/
      - media:/var/www/foodgram/media/
    depends_on:
      - backend
      - frontend