# Generated by Django 4.2.20 on 2025-04-09 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='г', max_length=50, unique=True, verbose_name='Еденица измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Тэг'),
        ),
    ]
