# Generated by Django 4.2.20 on 2025-04-14 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', verbose_name='Изображение рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=' ', unique=True, validators=[django.core.validators.RegexValidator(message='Для создания слага используйте буквы, числа и _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug тэга'),
            preserve_default=False,
        ),
    ]
